### ISSUE TITLE
Unable to Run IntegrationTest

### ISSUE THREAD

**Issue by atastrophic** [hivemq/hivemq-hello-world-extension#13]
I downloaded the source, built the extension and tried running the integration test. But it is unable to find `hivemq-hello-world-extension` on class path. The failing code is..

``` java
MountableFile.forClasspathResource("hivemq-hello-world-extension")
```

**Comment by SgtSilvio** [comment]
Hi @atastrophic 
Sorry for the late reply. To help resolve your issue, please answer the following questions.
1. How did you run the integration tests? (command line or IDE)
2. Does running `./gradlew integrationTest` on the command line work?
3. Maybe your IDE does not delegate to Gradle. Which IDE are you using?
